# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224,224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.33888319,0.33888319,0.33888319]
  PIXEL_STD: [0.32033292,0.32033292,0.32033292]
  TRANSFORMS: [ "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.0005
  MAX_EPOCH: 48
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-4
  WEIGHT_DECAY: 0.2
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98


TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"
TRAINER:
  MEDPROMPTCLIP:
    N_CTX_TEXT: 6
    CTX_INIT: "a MRI image of "
    PREC: "fp16"
    PROMPT_DEPTH_TEXT: 12
    GPT_PATH: "templates/Breast_MRI.json" # templates/pets_prompts_full.json
    USE_TEMPLATES: False
    USE_ATTRIBUTE_DATA: False
    EYE_DOMAIN: True
TEST:
  COMPUTE_CMAT: True