# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.74060887,0.53310455,0.70590561]
  PIXEL_STD: [0.1279016,0.16060114,0.11905577]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.005
  MAX_EPOCH: 72
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 3
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-4
  WEIGHT_DECAY: 0.1
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"
TRAINER:
  MEDPROMPTCLIP:
    N_CTX_TEXT: 6
    CTX_INIT: "a pathology image of"
    PREC: "fp16"
    PROMPT_DEPTH_TEXT: 9
    GPT_PATH: "templates/NCT.json" # templates/pets_prompts_full.json
    USE_TEMPLATES: False
    USE_ATTRIBUTE_DATA: False
    EYE_DOMAIN: False
TEST:
  COMPUTE_CMAT: True