# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5042229,0.50427837,0.5045664 ]
  PIXEL_STD: [0.22627175,0.22626996,0.22635411]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MEDPROMPTCLIP:
    CTX_INIT: "a X-ray image of"
    PREC: "fp16"
TEST:
  COMPUTE_CMAT: True

