# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.73547778,0.56929686,0.72280706]
  PIXEL_STD: [0.1290826,0.14607972,0.11514841]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MEDPROMPTCLIP:
    CTX_INIT: "a pathology image of"
    PREC: "fp16"
TEST:
  COMPUTE_CMAT: True

